### ISSUE TITLE
Error when run

### ISSUE THREAD

**Issue by Onotoko** [iitzco/widerface-to-tfrecord#1]
Hi,
Thanks for your post,
But I cannot found "wider_face_test_bbx_gt.txt"
Please let me know some information for this issue.
Thanks!

**Comment by iitzco** [comment]
Hi!

**Error if fixed now.**

The problem was that the test set does not contain bounding boxes. In case you convert the test set as well, the resulting `tfrecord` will contain images only without bounding boxes.

Leave a star if you found the project useful in order to help it grow! :)

**Comment by Onotoko** [comment]
Hi,
Thanks for quickly reply,
I just comment it :)
